[build]
  publish = "build"
  functions = "netlify/functions"

[dev]
  framework = "create-react-app"
  targetPort = 3001  # Cambia esto a un puerto diferente
  port = 8888        # Este es el puerto que Netlify Dev usará
  functions = "netlify/functions"
